-- CreateTable
CREATE TABLE "users" (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_name"  VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "status" BOOLEAN NOT NULL DEFAULT true
);

-- CreateTable
CREATE TABLE "incident" (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_name" VARCHAR(255) NOT NULL,
    "time_of_incident" TIMESTAMPTZ NOT NULL,
    "type" TEXT,
    "description" VARCHAR(500),
    "coordinates" TEXT ARRAY,

    FOREIGN KEY ("user_id") REFERENCES "users"("id")
);